library(tidyverse)
r_f <- readRDS("d:/Dropbox/Investigacion/Bloomberg_2025/Estimacion4/results/20260505_STABLE_V1/raw_data/res_spec_linear_s4_freeze.rds")
print("Structure of resM:")
print(names(r_f$resM))
print("Structure of resM$diag:")
print(names(r_f$resM$diag))
